# Generated by Django 6.1.1 on 2026-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
