# Generated by Django 6.1.1 on 2026-09-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_order_pickup_at_order_pickup_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=24),
        ),
    ]
