# Generated by Django 6.1.1 on 2026-09-10 14:32

import django.db.models.deletion
import tenants.uploads
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_media_keys(apps, schema_editor):
    tenant_model = apps.get_model("tenants", "Tenant")
    for tenant in tenant_model.objects.using(schema_editor.connection.alias).all().iterator():
        tenant.media_key = uuid.uuid4()
        tenant.save(update_fields=["media_key"], using=schema_editor.connection.alias)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_businesshour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, upload_to=tenants.uploads.logo_upload_path),
        ),
        migrations.AddField(
            model_name='tenant',
            name='media_key',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(populate_media_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tenant',
            name='media_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='unique_restaurant_member')],
            },
        ),
    ]
