# Generated by Django 6.1.1 on 2026-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_account_accountmembership_tenant_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
