# Generated by Django 6.1.1 on 2026-09-15 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_account_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_application_fee_fixed_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='stripe_application_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
