# Generated by Django 6.1.1 on 2026-09-09 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.menucategory'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='menuitemmodifiergroup',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='catalog.menuitem'),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='menuitemmodifiergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.modifiergroup'),
        ),
        migrations.AddField(
            model_name='modifieroption',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.modifiergroup'),
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='modifiergroup',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitemmodifiergroup',
            unique_together={('menu_item', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='modifieroption',
            unique_together={('group', 'name')},
        ),
    ]
