# Generated by Django 6.1.1 on 2026-09-10 14:32

import tenants.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_menuitemalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to=tenants.uploads.menu_upload_path),
        ),
    ]
