# Generated by Django 6.1.1 on 2026-09-10 15:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifieroption',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modifieroption',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
