# Generated by Django 6.1.1 on 2026-09-17 15:03

import django.db.models.deletion
from django.db import migrations, models


def seed_default_dietary_tags(apps, schema_editor):
    DietaryTag = apps.get_model("catalog", "DietaryTag")
    Tenant = apps.get_model("tenants", "Tenant")
    defaults = (("gluten_free", "Gluten-free"), ("vegetarian", "Vegetarian"), ("vegan", "Vegan"))
    for tenant in Tenant.objects.all().iterator():
        for slug, name in defaults:
            DietaryTag.objects.get_or_create(tenant_id=tenant.id, slug=slug, defaults={"name": name})


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_modifieroption_is_default_and_more'),
        ('tenants', '0008_tenant_address_line1_tenant_address_line2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=40)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_tags', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='catalog.dietarytag'),
        ),
        migrations.AddField(
            model_name='modifieroption',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, related_name='modifier_options', to='catalog.dietarytag'),
        ),
        migrations.RunPython(seed_default_dietary_tags, migrations.RunPython.noop),
    ]
