# Generated by Django 6.1.1 on 2026-09-21 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_dietary_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierOptionAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=80)),
                ('modifier_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.modifieroption')),
            ],
            options={
                'ordering': ['alias'],
                'unique_together': {('modifier_option', 'alias')},
            },
        ),
    ]
