# Generated by Django 6.1.1 on 2026-10-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_add_modifier_option_aliases"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategoryModifierGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required", models.BooleanField(blank=True, null=True)),
                ("min_choices", models.PositiveIntegerField(blank=True, null=True)),
                ("max_choices", models.PositiveIntegerField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_groups",
                        to="catalog.menucategory",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.modifiergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "unique_together": {("category", "group")},
            },
        ),
    ]
